name: CI
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash

      - name: Cache Buildozer Global Directory
        uses: actions/cache@v2
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}-${{ runner.os }}

      - name: Cache Buildozer
        uses: actions/cache@v2
        with:
          path: .buildozer
          key: buildozer-${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

      - name: Accept Android SDK Licenses
        run: echo "y" | ${{ runner.tool_cache }}/android-sdk/tools/bin/sdkmanager --licenses

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install --upgrade buildozer

      - name: Build with Buildozer
        run: buildozer android debug

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ github.workspace }}/.buildozer/android/platform/build/dists/*.apk
