name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Working Directory
        run: mkdir -p test_app

      - name: Install Buildozer and Cython
        run: |
          pip3 install --upgrade buildozer Cython
          export PATH=$PATH:~/.local/bin/

      - name: Install Android SDK components
        run: |
          sudo apt-get install -y openjdk-17-jdk
          yes | sdkmanager "build-tools;34.0.0" "platforms;android-34"

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Build with Buildozer
        run: |
          cd test_app
          buildozer init
          buildozer android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: test_app/bin/*.apk
