name: Build APK
on: [push, pull_request]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get install -y libgl1-mesa-dev
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
      - name: Install Modified kivy
        run: |
          pip install kivy

      - name: Install Cython
        run: |
          pip install Cython

      - name: Install Buildozer, Virtualenv, and Cython
        run: |
          pip3 install --user --upgrade Cython==0.29.33 virtualenv  # the --user should be removed if you do this in a venv
          export PATH=$PATH:~/.local/bin/

      - name: Build with Buildozer
        run: |
          export APP_ANDROID_ACCEPT_SDK_LICENSE=1
          export BUILDOZER_WARN_ON_ROOT=0
          cd ${{ github.workspace }}
          buildozer android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: bin/*.apk
