name: Build APK
on: [push, pull_request]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clone Kivy Repository
        run: |
          git clone https://github.com/kivy/kivy.git
      - name: Install GL dependencies
        run: sudo apt-get install -y libgl1-mesa-dev

      - name: Install Modified Kivy
        run: |
          cd kivy
          pip install .

      - name: Build with Buildozer
        run: |
          pip3 install --user --upgrade buildozer virtualenv
          export PATH=$PATH:~/.local/bin/
          export APP_ANDROID_ACCEPT_SDK_LICENSE=1
          export BUILDOZER_WARN_ON_ROOT=0
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          cd ${{ github.workspace }}
          buildozer android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: bin/*.apk
